const WINDY_CRAFT_ADMIN_THEME_KEY = 'WINDY_CRAFT_ADMIN_THEME_KEY';
const WINDY_CRAFT_ADMIN_TOKEN_KEY = 'WINDY_CRAFT_ADMIN_TOKEN_KEY';
const WINDY_CRAFT_ADMIN_AUTH_KEY = 'WINDY_CRAFT_ADMIN_AUTH_KEY';
const URL_BASE_SERVER = 'http://localhost:7003/api/v1/admin';

export const CONSTANTS = {
    WINDY_CRAFT_ADMIN_THEME_KEY,
    URL_BASE_SERVER,
    WINDY_CRAFT_ADMIN_AUTH_KEY,
    WINDY_CRAFT_ADMIN_TOKEN_KEY
};
